# action.yml
name: 'Build Image'
description: 'Build docker image'
inputs:
  docker-repository:  
    description: 'DockerHub repository to push to'
    required: true
  username:
    description: 'Docker username'
    required: true
  password:
    description: 'Docker password'
    required: true
  gh-repository:
    description: 'Github repository name'
    required: true
  gh-access-token:
    description: 'Github repository access token'
    required: true
  runner-tag:
    description: 'Tag for self-hosted runner'
    required: true
outputs:
  vars: # id of output
    description: 'Vars'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docker-repository }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.gh-repository }}
    - ${{ inputs.gh-access-token }}
    - ${{ inputs.runner-tag }}
